

function draw3dPieChart(result, canvasId, graphTitle) {

    var graphdata = result.d;

    var chartData = eval(graphdata.Data);
    var labelData = eval(graphdata.Label);
    var colorData = eval(graphdata.Color);

    var toolTipData = labelData + "<br/>" + chartData;
    /// <signature>
    /// <summary>Function to draw pie chart on given Canvas Id</summary>
    /// <param name="result">Data generated by RGraph class (generally response of webmethod)</param>
    /// <param name="canvasId" type="string">Canvas element Id</param>
    /// <param name="graphTitle" type="string">Graph Title</param>
    /// </signature>
    var pie = new RGraph.Pie({
        id: canvasId,
        data: chartData,
        options: {

            tooltips: toolTipData,
            labels: labelData,
            colors: colorData,
            variant: 'pie3d',
            labelsSticksList: true,
            labelsSticksColors: eval(graphdata.Colors),
            radius: 80,
            title: graphTitle

        }
    }).draw();
}